### ISSUE TITLE
allow triggers/builds from other repos

### ISSUE THREAD

**Issue by ramcq** [flathub-infra/buildbot-config#13]
Currently we only accept triggers and build modules which are defined in the flatpak repo - we should allow builds of modules whose .json file is hosted elsewhere, along with the upstream source for instance. A potential implementation would be to creating a module with a flatpak.json which specifics the other repo spec, acting as a "we believe this to be a legitimate origin of this package" attestation, and that the original review has been passed.

**Comment by alexlarsson** [comment]
This is supported in the force build scheduler ATM. Just paste in the git uri. It will not build official builds, but at least try builds.

**Comment by alexlarsson** [comment]
We now support configuring other repos for builds, for instance the current config: https://github.com/flathub/buildbot-config/blob/master/builds.json adds a org.kde.Sdk/5.9 repo. 
You can trigger a build of this by using the build name "org.kde.Sdk/5.9" in the force build page.

Technically it also will pick up change events and map them back from git repo url + branch to the actual thing to build. However, it needs some kind of change notification to be wired up to the repo. We're looking at doing that here: https://phabricator.kde.org/T7000

**Comment by bbhtt** [comment]
I don't think this is no longer desired. The current flow involves direct upload using flat-manager.
