### ISSUE TITLE
Make a shared repo for sources

### ISSUE THREAD

**Issue by alexlarsson** [flathub-infra/buildbot-config#16]
Many upstreams have pretty shitty networks, or move and stuff. It would be nice if we had a shared cache of all the sources downloaded.

We would need a pre-build step that ran `flatpak-builder --download-only`, and exports the result over http to the builders. Then the builders need to add --extra-sources-url=SOURCE-URL to the flatpak-builder commandline to pick these up.

**Comment by bbhtt** [comment]
This is run now.
