### ISSUE TITLE
Create temporary bundle for test builds

### ISSUE THREAD

**Issue by nedrichards** [flathub-infra/buildbot-config#22]
This is similar to #15 but different enough that I think it's a separate issue.

Having the ability to test builds that you're reviewing is really handy, but it can be hard to actually do deeper testing or debugging on a piece of software (it can build but might not run). It'd be handy if we could temporarily have access to a static bundle for a built app to run tests on.

**Comment by amtlib-dot-dll** [comment]
BTW, can we pull a specific revision from a Flatpak repo? For example, a revision pushed by a test build on pull requests. Currently we are only working on the `stable` branch

**Comment by TingPing** [comment]
We can't push all test builds to the repo for size and security reasons. Bundles make more sense for this uage.
