### ISSUE TITLE
Print title of step when it fails

### ISSUE THREAD

**Issue by hadess** [flathub-infra/buildbot-config#34]
When one of the buildbot steps fails, the only thing we see in the logs is the command itself, which isn't very helpful in diagnosing the problem for packagers to solve.

But the `steps` have names associated, which should be printed when the step fails. Then, the names could be expanded so they hint at the exact failure cause. Eg.

`Check for right id in AppStream xml` could be `Check that desktop file id matches Flatpak ID org.gnome.Test`

**Comment by bbhtt** [comment]
I think this works now? On hitting the `problems` expander, the step with the faliure expands automatically. Please reopen if not.

![image](https://github.com/user-attachments/assets/1426653a-043a-416b-8af9-d1b032a11847)
