### ISSUE TITLE
EOL KDE 5.10 SDK

### ISSUE THREAD

**Issue by nedrichards** [flathub-infra/buildbot-config#48]
The KDE 5.10 SDK does not currently build and needs to be turned down to prevent confusion and save some build cycles. There are no apps published on Flathub that use the KDE 5.10 runtime anymore. We should:
* Remove it from the autobuild queue when an FDo 1.6 update occurs
* Publish an EOL commit
* Anything else?

CC @aleixpol @ramcq @dbnicholson @alexlarsson

**Comment by aleixpol** [comment]
Sounds good to me. I'd say that it would be most important to streamline this process because it's bound to keep happening.

Soon Qt 5.12 (which is LTS) will be released and we'll go into the same process for 5.11 and eventually 5.9, so it would be useful to have deprecation warnings in place at least.

**Comment by ramcq** [comment]
We need an EOL reason to update the commits. Does this look like the correct list:
```
[buildbot@repo ~]$ ostree --repo=/srv/repo/repo refs | grep ^runtime/org.kde.*/5.10
runtime/org.kde.Sdk.Docs/arm/5.10
runtime/org.kde.Sdk.Locale/aarch64/5.10
runtime/org.kde.PlatformTheme.QGnomePlatform/x86_64/5.10
runtime/org.kde.Sdk.Locale/arm/5.10
runtime/org.kde.KStyle.Adwaita.Sources/x86_64/5.10
runtime/org.kde.Sdk.Debug/i386/5.10
runtime/org.kde.Platform/i386/5.10
runtime/org.kde.KStyle.HighContrast/i386/5.10
runtime/org.kde.Platform/x86_64/5.10
runtime/org.kde.KStyle.Adwaita/arm/5.10
runtime/org.kde.PlatformTheme.QGnomePlatform.Sources/x86_64/5.10
runtime/org.kde.Sdk.Locale/i386/5.10
runtime/org.kde.Platform.Locale/x86_64/5.10
runtime/org.kde.Platform.Locale/i386/5.10
runtime/org.kde.Sdk.Docs/aarch64/5.10
runtime/org.kde.Platform.Locale/arm/5.10
runtime/org.kde.Sdk/i386/5.10
runtime/org.kde.Sdk.Docs/i386/5.10
runtime/org.kde.Platform/aarch64/5.10
runtime/org.kde.Platform/arm/5.10
runtime/org.kde.KStyle.HighContrast/aarch64/5.10
runtime/org.kde.Sdk.Docs/x86_64/5.10
runtime/org.kde.Sdk.Debug/aarch64/5.10
runtime/org.kde.Sdk.Debug/x86_64/5.10
runtime/org.kde.KStyle.Adwaita/aarch64/5.10
runtime/org.kde.KStyle.HighContrast.Sources/x86_64/5.10
runtime/org.kde.PlatformTheme.QGnomePlatform/aarch64/5.10
runtime/org.kde.Sdk.Debug/arm/5.10
runtime/org.kde.Sdk.Locale/x86_64/5.10
runtime/org.kde.Sdk/arm/5.10
runtime/org.kde.Sdk/x86_64/5.10
runtime/org.kde.PlatformTheme.QGnomePlatform/arm/5.10
runtime/org.kde.KStyle.Adwaita/i386/5.10
runtime/org.kde.Platform.Locale/aarch64/5.10
runtime/org.kde.KStyle.HighContrast/x86_64/5.10
runtime/org.kde.Sdk/aarch64/5.10
runtime/org.kde.KStyle.Adwaita/x86_64/5.10
runtime/org.kde.PlatformTheme.QGnomePlatform/i386/5.10
runtime/org.kde.KStyle.HighContrast/arm/5.10
runtime/org.kde.Sdk.Sources/x86_64/5.10
```

**Comment by nedrichards** [comment]
That looks correct to me. For a message how about something like:
> Qt 5.10 ended standard support on 30th October 2018. Please migrate to a supported runtime.

**Comment by ramcq** [comment]
running:
`[buildbot@repo ~]$ ostree --repo=/srv/repo/repo refs | grep ^runtime/org.kde.*/5.10 | while read ref; do flatpak build-commit-from  --gpg-homedir=/srv/gpg-prod --gpg-sign=4184DD4D907A7CAE -v --force --no-update-summary --src-ref=$ref --end-of-life="Qt 5.10 ended standard support on 30th October 2018. Please migrate to a supported runtime." /srv/repo/repo $ref; done`

**Comment by TingPing** [comment]
> Sounds good to me. I'd say that it would be most important to streamline this process because it's bound to keep happening.

It may be the time to EOL GNOME 3.24 (no applications Flathub use it anymore).

**Comment by bbhtt** [comment]
Seems done.

```
flatpak remote-info --system flathub org.kde.Sdk//5.10
         ID: org.kde.Sdk
        Ref: runtime/org.kde.Sdk/x86_64/5.10
       Arch: x86_64
     Branch: 5.10
 Collection: org.flathub.Stable
   Download: 923.1 MB
  Installed: 2.6 GB

     Commit: b442774d6e703d4ec1f485a26b787a02c8999e99c9d275609c20bdd8b05f79a7
     Parent: c69822458c99d9f3c6665693181432bf3696a1c16b1a3f707ae3880ba7deb224
End-of-life: The KDE 5.10 SDK is no longer supported and does not receive security updates. We strongly recommend migrating to a supported SDK.
    Subject: Update to KF 5.46.0 (f6ecadb0)
       Date: 2018-05-15 23:13:26 +0000
```
