### ISSUE TITLE
add tarball freshness checker

### ISSUE THREAD

**Issue by ramcq** [flathub-infra/buildbot-config#8]
We should have a way to annotate / extend JSON files with patterns which we could feed to https://wiki.debian.org/debian/watch or similar, so we can automatically notify when recipes would benefit from updating.

**Comment by nanonyme** [comment]
So if I'm getting it right, annotation would have at least
* version
* optional dsc for validating the file
How does the trust normally work? Would the repo have trusted public keys pinned? I think it might make sense to do this in a way of extending upstream flatpak-builder (eg for validation) and then sharing the fields with that

**Comment by ramcq** [comment]
I imagine something like a "uscan" annotation which follows the formats supported by that tool - then it can be added to the .json as an attribute next to the URL for the tarball.

I think extending flatpak-builder to parse this and output them for uscan, or even invoke uscan, would be a nice approach. Because flatpak-builder uses json-glib to parse, and accepts /* C-style comments */ it's actually pretty irritating to handle the .json files from Python (although I guess you could just use json-glib via GI?).

Debian doesn't do any automatic task done other than notifying the maintainer that there is new stuff, so that's a good starting point and we could run that in buildbot periodically and send e-mails or open issues or whatever automatically, then if you wanted to make the maintainer's life easier you could go further and maybe output an updated source {} entry if a new thing is found.

**Comment by bbhtt** [comment]
This is done via fedc now.
