### ISSUE TITLE
weird buildbot anomaly (cache issue??)

### ISSUE THREAD

**Issue by FuchtelJockel** [flathub-infra/buildbot-config#81]
This only a occurs with the buildbot and I can't reproduce this at all with flatpak-builder.
If it tries to build opendht for:
https://github.com/flathub/net.jami.Jami
one or both arches fail with:
```
-- Looking for C++ include msgpack.hpp - not found
CMake Error at /usr/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.23/Modules/FindBoost.cmake:2376 (find_package_handle_standard_args)
  /usr/share/cmake-3.23/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /app/lib/cmake/msgpackc-cxx/msgpack-config.cmake:29 (find_dependency)
  CMakeLists.txt:64 (find_package)
```
This usually only happens if I don't change the opendht.yml file. If I add a change the success rate is much hire as seen in 
https://github.com/flathub/net.jami.Jami/commit/476bedd0f43f7b3c5df1335bd1435375365e929b
The build still failed for arbitrary reasons outside of my control but proofs my suspicion.
This should build just fine without libboost and any trickery. This issue plagues me for a while already and makes maintaining a project much more difficult.

**Comment by bbhtt** [comment]
I assume this was fixed later down the line. But the correct repo for infra issues is on https://github.com/flathub/flathub/
