### ISSUE TITLE
Cancel build on appstream errors.

### ISSUE THREAD

**Issue by LeSnake04** [flathub-infra/buildbot-config#82]
My recent build had an appstream error and for some reson the buildbot got stuck at ```dbus-daemon[1299926]: Reloaded configuration``` for over 30 min until I asked an admin to stop it.

The bot should probably stop after getting an ```Error: ERROR: appstream-compose failed: Child process exited with code 1``` in the stdout to avoid unnessary processes.

https://buildbot.flathub.org/#/builders/8/builds/12629

**Comment by bbhtt** [comment]
This should no longer happen after migration to libappstream https://docs.flathub.org/blog/improved-build-validation
